
-- Project Builder – Desarrollo de Emprendedores
-- Ejecutar en Supabase > SQL Editor

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    team_code text not null unique,
    project_name text not null,
    pin_salt text not null,
    pin_hash text not null,
    payload jsonb not null default '{"modulos": {}}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_projects_team_code
on public.projects(team_code);

-- Recomendación:
-- La app usa la SERVICE ROLE KEY únicamente como secreto del servidor de Streamlit.
-- No colocar esa llave dentro del repositorio.
-- No habilitar acceso directo del navegador a esta tabla.
