-- Project Builder MULTI v1
-- Ejecutar solo antes de que existan proyectos reales.
drop table if exists public.projects cascade;
drop table if exists public.teams cascade;
drop table if exists public.groups cascade;
drop table if exists public.app_users cascade;

create table public.app_users (
 id bigint generated by default as identity primary key,
 name text not null,
 email text not null unique,
 password_salt text not null,
 password_hash text not null,
 is_admin boolean not null default false,
 is_teacher boolean not null default true,
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table public.groups (
 id bigint generated by default as identity primary key,
 name text not null,
 teacher_id bigint not null references public.app_users(id) on delete restrict,
 period text,
 is_active boolean not null default true,
 created_at timestamptz not null default now()
);
create table public.teams (
 id bigint generated by default as identity primary key,
 group_id bigint not null references public.groups(id) on delete cascade,
 team_code text not null unique,
 team_name text not null,
 pin_salt text not null,
 pin_hash text not null,
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table public.projects (
 id bigint generated by default as identity primary key,
 team_id bigint not null unique references public.teams(id) on delete cascade,
 project_name text not null,
 payload jsonb not null default '{"modulos": {}}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index idx_groups_teacher on public.groups(teacher_id);
create index idx_teams_group on public.teams(group_id);
create index idx_projects_team on public.projects(team_id);
alter table public.app_users enable row level security;
alter table public.groups enable row level security;
alter table public.teams enable row level security;
alter table public.projects enable row level security;
